baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Shiro'
enableRobotsTXT = true

[params]
  description = 'A Content-focused theme for Hugo.'
  github = 'https://github.com/'
  email = 'hello@example.org'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[module]
  [module.hugoVersion]
    extended = true
    min = "0.123.6"

[markup]
  [markup.highlight]
    style = 'github'
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
