name = 'Shiro'
license = 'MIT'
licenselink = 'https://github.com/fuxieorg/hugo-theme-shiro/blob/main/LICENSE'
description = 'A Content-focused theme for Hugo.'

homepage = 'https://github.com/fuxieorg/hugo-theme-shiro'

demosite = 'https://hugo-theme-shiro.fuxie.org'

tags = ['blog', 'Content-focused']
features = ['No NPM dependencies']

[author]
  name = 'Fu Xie'
  homepage = 'https://fuxie.org/'
